name: test and publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  POETRY_VIRTUALENVS_CREATE: false

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - uses: knowsuchagency/poetry-install@v1.0
      - name: check black formatting
        run: inv check-black
      - name: mypy
        run: inv mypy
      - name: unit tests
        run: inv unit-tests
  publish:
    if: github.event_name != 'pull_request'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - uses: actions/checkout@v1
      - uses: knowsuchagency/poetry-install@v1.0
      - name: publish
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: inv publish
